### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [czerlun/Mastermind#1]
1. [Tu ma być `/usr/bin/python3`](https://github.com/czerlun/Mastermind/blob/c7dab5beac58b04cc16061c65fe2c4a453633b72/Mastermind.py#L1).
2. [To niepotrzebne](https://github.com/czerlun/Mastermind/blob/c7dab5beac58b04cc16061c65fe2c4a453633b72/Mastermind.py#L2).
3. [Proszę używać list i pętli](https://github.com/czerlun/Mastermind/blob/c7dab5beac58b04cc16061c65fe2c4a453633b72/Mastermind.py#L28).
4. [Jak będą listy, użyć `''.join()`](https://github.com/czerlun/Mastermind/blob/c7dab5beac58b04cc16061c65fe2c4a453633b72/Mastermind.py#L120).

**Comment by czerlun** [comment]
Proszę Pana spróbowałem naprawić błędy z Pana uwag. Przebudowałem projekt tak żeby posiadał 3 klasy oraz tak jak Pan mówił dwa obiekty. Przeskanowałem pylintem oraz poprawiłem to co mi wypisał.
Proszę o dalsze uwagi.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany.
1. [Nie importować rzeczy z modułów](https://github.com/czerlun/Mastermind/blob/87379912f0fb87bc861964c640cabf39c47c2af8/Mastermind.py#L2) (2. rozdział Poradnika).
2. [Tam, gdzie pasują, używać `True` i `False` zamiast `1` i `0`](https://github.com/czerlun/Mastermind/blob/87379912f0fb87bc861964c640cabf39c47c2af8/Mastermind.py#L41).
3. [Używać f-stringów zamiast sklejania](https://github.com/czerlun/Mastermind/blob/87379912f0fb87bc861964c640cabf39c47c2af8/Mastermind.py#L84) (2. rozdział).
4. [Nazwać stałą](https://github.com/czerlun/Mastermind/blob/87379912f0fb87bc861964c640cabf39c47c2af8/Mastermind.py#L106) (2. rozdział).
5. [Zły styl nazwy](https://github.com/czerlun/Mastermind/blob/87379912f0fb87bc861964c640cabf39c47c2af8/Mastermind.py#L52). Pylint!
6. [Z `x1` do `x4` zrobić listę; użyć pętli](https://github.com/czerlun/Mastermind/blob/87379912f0fb87bc861964c640cabf39c47c2af8/Mastermind.py#L112).
7. [Wtedy tutaj](https://github.com/czerlun/Mastermind/blob/87379912f0fb87bc861964c640cabf39c47c2af8/Mastermind.py#L142) można napisać `if [x.value() for x in self.interface.guess] == self.game.tab_results]:`.
8. [Z tego](https://github.com/czerlun/Mastermind/blob/87379912f0fb87bc861964c640cabf39c47c2af8/Mastermind.py#L158) zrobić funkcję `main()` (3. rozdział). Nadto zły styl nazw. Pylint!
9. [To](https://github.com/czerlun/Mastermind/blob/87379912f0fb87bc861964c640cabf39c47c2af8/Mastermind.py#L163) napisać raz, po `if...else`.
10. [Importy posortować; nie importować rzeczy z modułów](https://github.com/czerlun/Mastermind/blob/87379912f0fb87bc861964c640cabf39c47c2af8/Mastermind_test.py#L2) (2. rozdział).
11. [Testy nic nie testują](https://github.com/czerlun/Mastermind/blob/87379912f0fb87bc861964c640cabf39c47c2af8/Mastermind_test.py#L12). Każdą metodę nazwać `test_...()` i użyć w niej `self.assertEqual()`, `self.assertTrue()` itp. Na końcu pliku dopisać dwa magiczne wiersze (3. rozdział).

**Comment by czerlun** [comment]
Postarałem się poprawić projekt Proszę Pana. Jednak nie wiem jak ominąć problem z pętlą ( linijka 118 Mastermind.py ) oraz nie działa mi if na 156 linijce, chociaż tablice są identyczne. Bardzo proszę o dalsze uwagi.

**Comment by MarcinCiura** [comment]
1. [W tym miejscu](https://github.com/czerlun/Mastermind/blob/ccd884c3fe7f91254ec6f8b7eddbb7716ea98337/Mastermind.py#L18) zrobić za pomocą pętli 4-elementową listę `QSpinBox`-ów. Wtedy pętla z okolic 118. wiersza będzie się dała napisać.
2. W wierszu 156 nie użył Pan *list comprehension*, tylko *generator expression*, które nie tworzy listy, tylko generator. *List comprehensions* poznajemy po nawiasach kwadratowych `[...]`.

**Comment by czerlun** [comment]
Poprawiłem Proszę Pana te dwa błędy.

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość.
1. [To nie stała, tylko zmienna, więc małymi literami](https://github.com/czerlun/Mastermind/blob/f9d4f51806663a3c0b3cc6461329e734f5121669/Mastermind.py#L8) (2. rozdział).
2. [Z 12 zrobić stałą](https://github.com/czerlun/Mastermind/blob/f9d4f51806663a3c0b3cc6461329e734f5121669/Mastermind.py#L94) (2. rozdział).
3. [Co z pętlami, o które proszę od 24 dni](https://github.com/czerlun/Mastermind/blob/f9d4f51806663a3c0b3cc6461329e734f5121669/Mastermind.py#L103)?
4. [Zły styl nazwy](https://github.com/czerlun/Mastermind/blob/f9d4f51806663a3c0b3cc6461329e734f5121669/Mastermind.py#L60) (pylint!)
5. [`u` jest w alfabecie po `s`](https://github.com/czerlun/Mastermind/blob/f9d4f51806663a3c0b3cc6461329e734f5121669/Mastermind_test.py#L2).
6. [Złe spacje](https://github.com/czerlun/Mastermind/blob/f9d4f51806663a3c0b3cc6461329e734f5121669/Mastermind_test.py#L15) (pylint!)
7. [To nie są testy](https://github.com/czerlun/Mastermind/blob/f9d4f51806663a3c0b3cc6461329e734f5121669/Mastermind_test.py#L21), bo nie ma w nich żadnych `.assert,,,()`.

**Comment by czerlun** [comment]
Zastosowałem się do Pana uwag, poprawiłem projekt.

**Comment by MarcinCiura** [comment]
[Wyrzucić te 6 wierszy](https://github.com/czerlun/Mastermind/blob/d173b01eb6df61a44c61c7fc22a4b0880690939d/Mastermind_test.py#L42). `unittest.main()` robi właśnie to samo, co one, tylko poprawnie, czyli wywołuje `.setUp()` przed każdą metodą oraz naprawdę wywołuje `.test_oszust()` i `.test_reset()`, a nie tylko wzmiankuje ich nazwy (gdzie był pylint?)

**Comment by czerlun** [comment]
Usunąłęm Proszę Pana niepoprawne wiersze. Czy projekt jest już zaliczony?

**Comment by MarcinCiura** [comment]
Tak, wczoraj przekazałem tę wiadomość drowi Gąciarzowi. Ale Pan niech jeszcze:
1. Posortuje jak należy importy w module z testami (2. rozdział).
2. Usunie dwa niepotrzebne wiersze z końca tego modułu: zmienne globalne `game` i `widget` w ogóle nie są używane.

**Comment by czerlun** [comment]
Dziękuję bardzo za wszystkie rady oraz za pomoc w projekcie :) Bardzo dużo się od Pana nauczyłem.
